# Generated by Django 3.2.2 on 2021-05-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_fdsignup_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fdsignup',
            table='fdsignup_table',
        ),
    ]
