# Generated by Django 3.2.2 on 2021-05-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_fdsignup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fdmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothfile', models.FileField(upload_to='')),
                ('clothtype', models.CharField(max_length=100)),
                ('clothcolour', models.CharField(max_length=100)),
                ('clothpattern', models.CharField(max_length=100)),
                ('clothsizes', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fdmodels_table',
            },
        ),
    ]
