# Generated by Django 3.2.2 on 2021-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fdmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdmodels',
            name='clothfile',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
    ]
