# Generated by Django 3.2.2 on 2021-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210508_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fdform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothfile', models.ImageField(default='', upload_to='media/image')),
                ('clothtype', models.CharField(max_length=100)),
                ('clothcolour', models.CharField(max_length=100)),
                ('clothpattern', models.CharField(max_length=100)),
                ('clothsizes', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fdform_table',
            },
        ),
        migrations.DeleteModel(
            name='Fdmodel',
        ),
    ]
