# Generated by Django 3.2.2 on 2021-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210508_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdform',
            name='clothgender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
