# Generated by Django 3.2.2 on 2021-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fdform_clothgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdform',
            name='clothname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
