# Generated by Django 3.2.2 on 2021-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210511_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdform',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
