# Generated by Django 3.2.2 on 2021-05-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_cusignup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdform',
            name='username',
        ),
    ]
