# Generated by Django 3.2.2 on 2021-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210512_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuitems',
            name='clothgender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
