# Generated by Django 3.2.2 on 2021-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cuitems_clothgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuitems',
            name='clothcolour',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cuitems',
            name='clothpattern',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cuitems',
            name='clothsizes',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cuitems',
            name='clothtype',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
