# Generated by Django 3.2.2 on 2021-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210512_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuitems',
            name='clothgender',
            field=models.CharField(max_length=100),
        ),
    ]
