# Generated by Django 3.2.2 on 2021-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210512_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuitems',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
