# Generated by Django 3.2.2 on 2021-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cuitems_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuitems',
            name='clothdesigner',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
