# Generated by Django 3.2.2 on 2021-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20210516_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuitems',
            name='cart',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuitems',
            name='wishlist',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
