# Generated by Django 3.2.2 on 2021-05-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20210516_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuitems',
            name='order',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
